Repository commercelayer/commercelayer-react-components, pull requests merged in 2023-10, with the labels that each got.

#422 Move README.md under 'react-components' package folder
  README.md
  packages/react-components/README.md
Labels: documentation

#427 feat: Add `invertAddresses` prop to `<AddressesContainer/>`
  packages/react-components/specs/addresses/invert-addresses.spec.tsx
  packages/react-components/src/components/addresses/AddressInput.tsx
  packages/react-components/src/components/addresses/AddressesContainer.tsx
  packages/react-components/src/components/addresses/SaveAddressesButton.tsx
  packages/react-components/src/context/BillingAddressFormContext.ts
  packages/react-components/src/reducers/AddressReducer.ts
  packages/react-components/src/typings/index.ts
  packages/react-components/src/utils/addressesManager.ts
Labels: enhancement

#429 Avoid `ShippingMethodRadioButton` to lose focus when selected
  packages/react-components/src/components/shipping_methods/ShippingMethodRadioButton.tsx
Labels: bug

#436 Prevent empty list of orders or subscriptions to break the rendering
  lerna.json
  packages/react-components/package.json
  packages/react-components/src/components/orders/OrderList.tsx
Labels: bug

#437 v4.7.2
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release

#439 v4.7.3
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release

#441 v4.7.4
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release

#443 Fix `OrderList` pagination pageIndex
  packages/react-components/src/components/orders/OrderList.tsx
Labels: bug
