Repository commercelayer/commercelayer-react-components, pull requests merged in 2023-11, with the labels that each got.

#446 fix: Filters line items by type on country lock
  packages/react-components/src/utils/addressesManager.ts
Labels: bug

#447 fix: Show payments methods not compatible with express payment on the cart.
  packages/react-components/src/components/orders/HostedCart.tsx
  packages/react-components/src/components/payment_gateways/PaymentGateway.tsx
  packages/react-components/src/components/payment_source/PaymentSource.tsx
Labels: bug

#445 Allow line_items update using external_price
  packages/react-components/src/components/line_items/LineItemQuantity.tsx
  packages/react-components/src/components/line_items/LineItemsContainer.tsx
  packages/react-components/src/reducers/LineItemReducer.ts
Labels: enhancement

#449 chore: Remove console.log
  packages/react-components/src/components/line_items/LineItemsCount.tsx
Labels: ignore-for-release

#451 Add ability to override Country list or to extends pre-defined list of States
  lerna.json
  packages/react-components/package.json
  packages/react-components/src/components/addresses/AddressCountrySelector.tsx
  packages/react-components/src/components/addresses/AddressStateSelector.tsx
  packages/react-components/src/components/customers/CustomerAddressForm.tsx
  packages/react-components/src/utils/countryStateCity.ts
  packages/react-components/src/utils/isEmptyStates.ts
  pnpm-lock.yaml
Labels: enhancement

#452 fix: Expose props to custom component function
  lerna.json
  packages/react-components/package.json
  packages/react-components/src/components/customers/CustomerInput.tsx
  packages/react-components/src/components/payment_source/ExternalPayment.tsx
  packages/react-components/src/utils/validateFormFields.ts
  pnpm-lock.yaml
Labels: bug

#454 fix: Customer email validation.
  packages/react-components/src/components/customers/CustomerInput.tsx
  packages/react-components/src/utils/validateFormFields.ts
Labels: bug

#455 fix: Add customer email validation into `SaveAddressesButton`.
  packages/react-components/src/components/addresses/SaveAddressesButton.tsx
  packages/react-components/src/components/customers/CustomerInput.tsx
Labels: bug
