Repository commercelayer/commercelayer-react-components, pull requests merged in 2024-08, with the labels that each got.

#565 Update `js-auth` library in the documentation package
  packages/docs/package.json
  packages/docs/stories/_internals/useGetToken.ts
  pnpm-lock.yaml
Labels: enhancement

#567 Change checkout url using the buy now mode
  packages/react-components/src/components/orders/CheckoutLink.tsx
  packages/react-components/src/reducers/OrderReducer.ts
Labels: bug

#568 v4.15.6
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release

#569 Read org configuration for buy now mode
  lerna.json
  packages/react-components/package.json
  packages/react-components/src/components/orders/AddToCartButton.tsx
  packages/react-components/src/components/orders/PlaceOrderButton.tsx
  packages/react-components/src/components/payment_gateways/AdyenGateway.tsx
  packages/react-components/src/components/payment_gateways/BraintreeGateway.tsx
  packages/react-components/src/components/payment_gateways/CheckoutComGateway.tsx
  packages/react-components/src/components/payment_gateways/ExternalGateway.tsx
  packages/react-components/src/components/payment_gateways/KlarnaGateway.tsx
  packages/react-components/src/components/payment_gateways/PaypalGateway.tsx
  packages/react-components/src/components/payment_gateways/StripeGateway.tsx
  packages/react-components/src/components/payment_gateways/WireTransferGateway.tsx
  packages/react-components/src/components/payment_source/AdyenPayment.tsx
  packages/react-components/src/components/payment_source/CheckoutComPayment.tsx
  packages/react-components/src/components/payment_source/PaymentSource.tsx
  packages/react-components/src/reducers/OrderReducer.ts
  packages/react-components/src/utils/getCardDetails.ts
  pnpm-lock.yaml
Labels: bug

#570 v4.15.7
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release

#571 Address fields
  lerna.json
  packages/react-components/package.json
  packages/react-components/src/components/addresses/AddressStateSelector.tsx
  packages/react-components/src/components/orders/CheckoutLink.tsx
  packages/react-components/src/components/utils/BaseSelect.tsx
Labels: bug

#572 v4.15.8
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release

#574 Update Order: Set customer address using the `invertAddresses` prop
  lerna.json
  package.json
  packages/react-components/package.json
  packages/react-components/src/components/addresses/AddressesContainer.tsx
  packages/react-components/src/components/addresses/SaveAddressesButton.tsx
  packages/react-components/src/context/AddressContext.ts
  packages/react-components/src/reducers/AddressReducer.ts
  packages/react-components/src/reducers/CustomerReducer.ts
  packages/react-components/src/utils/addressesManager.ts
  pnpm-lock.yaml
Labels: bug

#575 Display Braintree 3DS Error Messages
  packages/react-components/package.json
  packages/react-components/src/components/payment_source/BraintreePayment.tsx
  pnpm-lock.yaml
Labels: bug

#576 v4.15.9
  lerna.json
  packages/react-components/package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#577 Remove `axios` dependency
  package.json
  packages/react-components/package.json
  packages/react-components/src/context/ExternalFunctionContext.ts
  pnpm-lock.yaml
Labels: bug
