Repository commercelayer/commercelayer-react-components, pull requests merged in 2024-07, with the labels that each got.

#544 Fix typo in documentation
  packages/docs/stories/examples/checkout/000.intro.mdx
  packages/docs/stories/examples/customer/000.intro.mdx
  packages/docs/stories/getting-started/001.introduction.mdx
Labels: documentation

#546 v4.14.3
  lerna.json
  packages/react-components/package.json
Labels: bug

#547 Allows the shopper to remove a stored payment method.
  lerna.json
  packages/react-components/package.json
  packages/react-components/src/components/payment_source/AdyenPayment.tsx
Labels: bug

#548 v4.14.4
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release

#549 Allows the shopper to remove a stored payment method.
  packages/react-components/src/components/payment_source/AdyenPayment.tsx
Labels: bug

#550 v4.14.5
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release

#551 Add multi fields validation
  lerna.json
  packages/docs/stories/examples/checkout/002.addresses.stories.tsx
  packages/react-components/package.json
  packages/react-components/src/components/addresses/AddressStateSelector.tsx
  packages/react-components/src/components/addresses/BillingAddressForm.tsx
  packages/react-components/src/components/addresses/ShippingAddressForm.tsx
  packages/react-components/src/reducers/AddressReducer.ts
Labels: enhancement

#552 v4.15.0
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release

#553 Fix missing customer address reference
  packages/react-components/src/reducers/CustomerReducer.ts
Labels: bug

#554 v4.15.1
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release

#557 v4.15.2
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release

#558 Checkout link provided by organization config
  lerna.json
  packages/react-components/package.json
  packages/react-components/src/components/customers/MyAccountLink.tsx
  packages/react-components/src/components/orders/CheckoutLink.tsx
Labels: bug

#559 v4.15.3
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release

#560 Set adyen shopper ip
  packages/react-components/src/components/payment_source/AdyenPayment.tsx
Labels: bug

#561 v4.15.4
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release

#563 Set right attribute for shopper ip
  packages/react-components/src/components/payment_source/AdyenPayment.tsx
Labels: bug

#564 v4.15.5
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release
