Repository commercelayer/commercelayer-react-components, pull requests merged in 2024-02, with the labels that each got.

#476 feat: Add subscriptions helpers
  lerna.json
  package.json
  packages/react-components/package.json
  packages/react-components/src/components/addresses/Address.tsx
  packages/react-components/src/components/addresses/AddressStateSelector.tsx
  packages/react-components/src/components/addresses/BillingAddressForm.tsx
  packages/react-components/src/components/addresses/ShippingAddressForm.tsx
  packages/react-components/src/components/auth/CommerceLayer.tsx
  packages/react-components/src/components/customers/CustomerAddressForm.tsx
  packages/react-components/src/components/customers/CustomerContainer.tsx
  packages/react-components/src/components/customers/CustomerInput.tsx
  packages/react-components/src/components/customers/MyAccountLink.tsx
  packages/react-components/src/components/customers/SaveCustomerButton.tsx
  packages/react-components/src/components/gift_cards/GiftCard.tsx
  packages/react-components/src/components/in_stock_subscriptions/InStockSubscriptionButton.tsx
  packages/react-components/src/components/line_items/LineItemsContainer.tsx
  packages/react-components/src/components/orders/AddToCartButton.tsx
  packages/react-components/src/components/orders/HostedCart.tsx
  packages/react-components/src/components/orders/OrderList.tsx
  packages/react-components/src/components/orders/OrderListRow.tsx
  packages/react-components/src/components/orders/PlaceOrderButton.tsx
  packages/react-components/src/components/payment_gateways/AdyenGateway.tsx
  packages/react-components/src/components/payment_methods/PaymentMethodRadioButton.tsx
  packages/react-components/src/components/payment_methods/PaymentMethodsContainer.tsx
  packages/react-components/src/components/payment_source/AdyenPayment.tsx
  packages/react-components/src/components/payment_source/BraintreePayment.tsx
  packages/react-components/src/components/payment_source/CheckoutComPayment.tsx
  packages/react-components/src/components/payment_source/KlarnaPayment.tsx
  packages/react-components/src/components/payment_source/StripeExpressPayment.tsx
  packages/react-components/src/components/payment_source/StripePayment.tsx
  packages/react-components/src/components/prices/Price.tsx
  packages/react-components/src/components/shipping_methods/ShippingMethod.tsx
  packages/react-components/src/components/utils/BaseField.tsx
  packages/react-components/src/components/utils/PriceTemplate.tsx
  packages/react-components/src/components/utils/getAllErrors.tsx
  packages/react-components/src/context/CustomerContext.ts
  packages/react-components/src/hooks/useCustomerContainer.ts
  packages/react-components/src/reducers/CustomerReducer.ts
  packages/react-components/src/reducers/GiftCardReducer.ts
  packages/react-components/src/reducers/OrderReducer.ts
  packages/react-components/src/reducers/PaymentMethodReducer.ts
  packages/react-components/src/utils/customMessages.ts
  packages/react-components/src/utils/expressPaymentHelper.ts
  packages/react-components/src/utils/filterChildren.ts
  packages/react-components/src/utils/getCustomerIdByToken.ts
  packages/react-components/src/utils/getDomain.ts
  packages/react-components/src/utils/getPrices.tsx
  packages/react-components/src/utils/isGuestToken.ts
  packages/react-components/src/utils/jwt.ts
  packages/react-components/src/utils/triggerAttributeHelper.ts
  packages/react-components/src/utils/validateFormFields.ts
  packages/react-components/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#482 Add new prop `customFieldErrorMessage` to billing and shippping address form components
  lerna.json
  package.json
  packages/react-components/mocks/handlers.ts
  packages/react-components/mocks/server.ts
  packages/react-components/package.json
  packages/react-components/pnpm-lock.yaml
  packages/react-components/src/components/addresses/BillingAddressForm.tsx
  packages/react-components/src/components/addresses/ShippingAddressForm.tsx
  packages/react-components/src/components/payment_source/CheckoutComPayment.tsx
  packages/react-components/src/components/payment_source/StripeExpressPayment.tsx
  packages/react-components/src/components/payment_source/StripePayment.tsx
  packages/react-components/src/index.ts
  packages/react-components/src/reducers/AddressReducer.ts
  packages/react-components/src/utils/addressesManager.ts
  packages/react-components/src/utils/validateFormFields.ts
  packages/react-components/tsconfig.json
  packages/react-components/vitest.config.mts
  pnpm-lock.yaml
Labels: enhancement

#483 fix: Improve the retrieval of orders of an order subscription
  packages/react-components/src/components/customers/CustomerContainer.tsx
  packages/react-components/src/components/orders/OrderList.tsx
  packages/react-components/src/reducers/CustomerReducer.ts
Labels: bug

#484 Fix CI pnpm install error
  .github/workflows/publish.yaml
Labels: ignore-for-release

#486 Fix build components
  package.json
  packages/react-components/package.json
  packages/react-components/src/components/payment_source/CheckoutComPayment.tsx
  packages/react-components/src/components/payment_source/StripeExpressPayment.tsx
  packages/react-components/src/components/payment_source/StripePayment.tsx
  pnpm-lock.yaml
Labels: ignore-for-release

#487 Enforce `OrderList` data for subscription orders
  packages/react-components/src/components/orders/OrderList.tsx
Labels: bug

#488 Fix: fix conditional in `OrderList` data calculation
  packages/react-components/src/components/orders/OrderList.tsx
Labels: bug

#489 Docs: Add example of how to customize countries and states lists
  packages/docs/package.json
  packages/docs/stories/_internals/useGetToken.ts
  packages/docs/stories/examples/customer/002.address-form.mdx
  pnpm-lock.yaml
Labels: documentation

#492 Show custom error message
  packages/docs/.storybook/addon-gh-repository/Tool.tsx
  packages/docs/mocks/browser.js
  packages/docs/mocks/data/adjustments.js
  packages/docs/mocks/data/bundles.js
  packages/docs/mocks/data/line_items.js
  packages/docs/mocks/data/markets.js
  packages/docs/mocks/data/orders.js
  packages/docs/mocks/data/tags.js
  packages/docs/package.json
  packages/docs/stories/_internals/useGetToken.ts
  packages/docs/stories/examples/checkout/002.addresses.mdx
  packages/docs/stories/examples/checkout/002.addresses.stories.tsx
  packages/react-components/package.json
  packages/react-components/src/components/addresses/AddressInput.tsx
  packages/react-components/src/components/addresses/BillingAddressForm.tsx
  packages/react-components/src/components/addresses/ShippingAddressForm.tsx
  packages/react-components/src/components/orders/OrderListPaginationButtons.tsx
  packages/react-components/src/components/payment_source/CheckoutComPayment.tsx
  packages/react-components/src/components/payment_source/PaymentSourceDetail.tsx
  packages/react-components/src/components/payment_source/StripeExpressPayment.tsx
  packages/react-components/src/components/payment_source/StripePayment.tsx
  packages/react-components/src/reducers/AvailabilityReducer.ts
  packages/react-components/src/utils/getApplicationLink.ts
  pnpm-lock.yaml
Labels: bug

#493 v4.10.2
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release

#494 Fix gh-pages deploy
  .github/workflows/gh-pages.yaml
  .github/workflows/publish.yaml
Labels: ignore-for-release

#495 Manage metadata fields into the address form
  packages/react-components/src/components/addresses/AddressInputSelect.tsx
  packages/react-components/src/components/addresses/BillingAddressForm.tsx
  packages/react-components/src/components/addresses/SaveAddressesButton.tsx
  packages/react-components/src/index.ts
  packages/react-components/src/utils/addressesManager.ts
  packages/react-components/src/utils/validateFormFields.ts
Labels: enhancement

#496 Add documentation about metadata fields
  packages/docs/stories/examples/customer/002.address-form.mdx
  packages/docs/stories/examples/customer/002.address-form.stories.tsx
Labels: documentation

#497 v4.11.0
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release
