Repository commercelayer/commercelayer-react-components, pull requests merged in 2024-03, with the labels that each got.

#499 Avoid changing payment source when placing the order.
  lerna.json
  packages/react-components/package.json
  packages/react-components/src/components/payment_gateways/PaymentGateway.tsx
  packages/react-components/src/components/payment_gateways/WireTransferGateway.tsx
  packages/react-components/src/components/payment_source/AdyenPayment.tsx
  packages/react-components/src/components/payment_source/BraintreePayment.tsx
  packages/react-components/src/components/payment_source/CheckoutComPayment.tsx
  packages/react-components/src/components/payment_source/PaypalPayment.tsx
  packages/react-components/src/components/payment_source/WireTransferPayment.tsx
  packages/react-components/src/utils/addressesManager.ts
  packages/react-components/src/utils/canPlaceOrder.ts
  packages/react-components/src/utils/validateFormFields.ts
Labels: bug

#501 Fx typo in states documentation
  packages/docs/stories/examples/customer/002.address-form.mdx
Labels: documentation

#500 Update customer payment source of a subscription after order place
  lerna.json
  packages/docs/stories/examples/checkout/002.addresses.stories.tsx
  packages/react-components/package.json
  packages/react-components/specs/in_stock_subscriptions/in_stock_subscriptions.spec.tsx
  packages/react-components/src/components/addresses/AddressInput.tsx
  packages/react-components/src/components/addresses/BillingAddressForm.tsx
  packages/react-components/src/components/addresses/ShippingAddressForm.tsx
  packages/react-components/src/components/errors/Errors.tsx
  packages/react-components/src/components/utils/BaseInput.tsx
  packages/react-components/src/reducers/AddressReducer.ts
  packages/react-components/src/reducers/PlaceOrderReducer.ts
  packages/react-components/src/utils/hasSubscriptions.ts
  packages/react-components/src/utils/updateOrderSubscriptionCustomerPaymentSource.ts
Labels: enhancement

#503 v4.11.2
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release

#504 Deprecate `pattern` prop on AddressInput component
  lerna.json
  packages/docs/stories/examples/checkout/002.addresses.stories.tsx
  packages/react-components/package.json
  packages/react-components/src/components/addresses/AddressInput.tsx
  packages/react-components/src/components/addresses/BillingAddressForm.tsx
  packages/react-components/src/components/addresses/ShippingAddressForm.tsx
Labels: bug

#505 v4.11.3
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release

#506 Add `codeType` to gift card or coupon code components
  lerna.json
  packages/docs/stories/examples/cart/001.cart.mdx
  packages/docs/stories/examples/cart/001.cart.stories.tsx
  packages/react-components/package.json
  packages/react-components/src/components/addresses/BillingAddressForm.tsx
  packages/react-components/src/components/addresses/ShippingAddressForm.tsx
  packages/react-components/src/components/gift_cards/GiftCardOrCouponCode.tsx
  packages/react-components/src/components/gift_cards/GiftCardOrCouponForm.tsx
  packages/react-components/src/components/gift_cards/GiftCardOrCouponInput.tsx
  packages/react-components/src/components/gift_cards/GiftCardOrCouponRemoveButton.tsx
  packages/react-components/src/reducers/OrderReducer.ts
Labels: enhancement

#508 v4.12.0
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release
