Repository commercelayer/commercelayer-react-components, pull requests merged in 2025-10, with the labels that each got.

#670 Enable server side sorting for order subscriptions
  packages/react-components/src/components/customers/CustomerContainer.tsx
  packages/react-components/src/components/orders/OrderList.tsx
  packages/react-components/src/reducers/CustomerReducer.ts
Labels: enhancement

#667 Enhance customer resources requests
  packages/react-components/src/components/customers/CustomerContainer.tsx
  packages/react-components/src/reducers/CustomerReducer.ts
Labels: enhancement

#672 Fix save address input behaviour
  packages/react-components/src/components/addresses/AddressInput.tsx
  packages/react-components/src/components/addresses/BillingAddressForm.tsx
  packages/react-components/src/components/addresses/ShippingAddressForm.tsx
  packages/react-components/src/components/orders/OrderContainer.tsx
  packages/react-components/src/components/utils/BaseInput.tsx
  packages/react-components/src/context/BillingAddressFormContext.ts
  packages/react-components/tsconfig.prod.json
Labels: bug

#673 v4.28.0
  lerna.json
  packages/react-components/package.json
Labels: ignore-for-release
